# -*- coding: utf-8 -*-
"""M24AID016_BJyothi_Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AiYfWlGLVETgJTWM_289ea6tA3-ldQj-
"""

!pip install numpy pandas scipy matplotlib blake3 -q

# !pip install numpy pandas scipy matplotlib blake3 -q

import hashlib, hmac, os, time, math, random, string, secrets

# ---- BLAKE3 (added in extension work) -------------------------------------
# BLAKE3 (2020) is the successor to BLAKE2. It uses a reduced-round (7) BLAKE2
# core inside a Merkle-tree mode, which lets a SINGLE large input be hashed in
# parallel -- something SHA-3's sequential sponge and plain BLAKE2b cannot do.
# It is not in the standard library, so we use the official `blake3` package.
try:
    from blake3 import blake3 as _blake3
    HAS_BLAKE3 = True
except ImportError:
    HAS_BLAKE3 = False
    print("[warn] blake3 not installed. Run:  !pip install blake3 -q")

def b3_digest(data, length=32):
    """BLAKE3 digest (default 32B; XOF allows any length)."""
    return _blake3(data).digest(length=length)

def b3_keyed(data, key32, length=32):
    """BLAKE3 native keyed MAC. Key MUST be exactly 32 bytes."""
    return _blake3(data, key=key32).digest(length=length)
# ---------------------------------------------------------------------------

import multiprocessing
from collections import Counter
from math import log2, sqrt

import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

os.makedirs("sem2_output", exist_ok=True)
M64 = 0xFFFFFFFFFFFFFFFF



# 1 — PURE PYTHON SHA-3 (for modifications)


KECCAK_RC = [
    0x0000000000000001, 0x0000000000008082, 0x800000000000808A,
    0x8000000080008000, 0x000000000000808B, 0x0000000080000001,
    0x8000000080008081, 0x8000000000008009, 0x000000000000008A,
    0x0000000000000088, 0x0000000080008009, 0x000000008000000A,
    0x000000008000808B, 0x800000000000008B, 0x8000000000008089,
    0x8000000000008003, 0x8000000000008002, 0x8000000000000080,
    0x000000000000800A, 0x800000008000000A, 0x8000000080008081,
    0x8000000000008080, 0x0000000080000001, 0x8000000080008008,
]
KECCAK_ROT = [
     0,  1, 62, 28, 27, 36, 44,  6, 55, 20,
     3, 10, 43, 25, 39, 41, 45, 15, 21,  8,
    18,  2, 61, 56, 14,
]

def _rot64(v, n):
    return ((v << n) | (v >> (64 - n))) & M64

def keccak_f1600(state, num_rounds=24):
    A = list(state)
    for rc in KECCAK_RC[:num_rounds]:
        C = [A[x]^A[x+5]^A[x+10]^A[x+15]^A[x+20] for x in range(5)]
        D = [C[(x-1)%5] ^ _rot64(C[(x+1)%5], 1) for x in range(5)]
        A = [A[i] ^ D[i%5] for i in range(25)]
        B = [0]*25
        for x in range(5):
            for y in range(5):
                B[y+5*((2*x+3*y)%5)] = _rot64(A[x+5*y], KECCAK_ROT[x+5*y])
        A = [B[x+5*y]^((B[(x+1)%5+5*y]^M64)&B[(x+2)%5+5*y])
             for y in range(5) for x in range(5)]
        A[0] ^= rc
    return A

def sha3_pure(data, num_rounds=24, rate_bytes=136, digest_bytes=32):
    RATE = rate_bytes
    msg = bytearray(data) + bytearray([0x06])
    while len(msg) % RATE: msg.append(0x00)
    msg[-1] |= 0x80
    state = [0]*25
    for blk in range(0, len(msg), RATE):
        for i in range(RATE//8):
            state[i] ^= int.from_bytes(msg[blk+i*8:blk+i*8+8], 'little')
        state = keccak_f1600(state, num_rounds)
    out = b''
    while len(out) < digest_bytes:
        out += b''.join(state[i].to_bytes(8,'little') for i in range(RATE//8))
        if len(out) < digest_bytes: state = keccak_f1600(state, num_rounds)
    return out[:digest_bytes]



# 2 — PURE PYTHON BLAKE2b (for FastRounds mod)


BLAKE2B_IV = [
    0x6A09E667F3BCC908, 0xBB67AE8584CAA73B,
    0x3C6EF372FE94F82B, 0xA54FF53A5F1D36F1,
    0x510E527FADE682D1, 0x9B05688C2B3E6C1F,
    0x1F83D9ABFB41BD6B, 0x5BE0CD19137E2179,
]
BLAKE2B_SIGMA = [
    [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,15],
    [14,10, 4, 8, 9,15,13, 6, 1,12, 0, 2,11, 7, 5, 3],
    [11, 8,12, 0, 5, 2,15,13,10,14, 3, 6, 7, 1, 9, 4],
    [ 7, 9, 3, 1,13,12,11,14, 2, 6, 5,10, 4, 0,15, 8],
    [ 9, 0, 5, 7, 2, 4,10,15,14, 1,11,12, 6, 8, 3,13],
    [ 2,12, 6,10, 0,11, 8, 3, 4,13, 7, 5,15,14, 1, 9],
    [12, 5, 1,15,14,13, 4,10, 0, 7, 6, 3, 9, 2, 8,11],
    [13,11, 7,14,12, 1, 3, 9, 5, 0,15, 4, 8, 6, 2,10],
    [ 6,15,14, 9,11, 3, 0, 8,12, 2,13, 7, 1, 4,10, 5],
    [10, 2, 8, 4, 7, 6, 1, 5,15,11, 9,14, 3,12,13, 0],
]

def _ror64(v, n): return ((v >> n) | (v << (64-n))) & M64

def _b2G(v, a, b, c, d, x, y):
    v[a]=(v[a]+v[b]+x)&M64; v[d]=_ror64(v[d]^v[a],32)
    v[c]=(v[c]+v[d])  &M64; v[b]=_ror64(v[b]^v[c],24)
    v[a]=(v[a]+v[b]+y)&M64; v[d]=_ror64(v[d]^v[a],16)
    v[c]=(v[c]+v[d])  &M64; v[b]=_ror64(v[b]^v[c],63)

def _b2_compress(h, blk, t, last, rounds):
    m=[int.from_bytes(blk[i*8:(i+1)*8],'little') for i in range(16)]
    v=list(h)+list(BLAKE2B_IV)
    v[12]^=t&M64; v[13]^=(t>>64)&M64
    if last: v[14]^=M64
    for r in range(rounds):
        s=BLAKE2B_SIGMA[r%10]
        _b2G(v,0,4, 8,12,m[s[0]], m[s[1]]); _b2G(v,1,5, 9,13,m[s[2]], m[s[3]])
        _b2G(v,2,6,10,14,m[s[4]], m[s[5]]); _b2G(v,3,7,11,15,m[s[6]], m[s[7]])
        _b2G(v,0,5,10,15,m[s[8]], m[s[9]]); _b2G(v,1,6,11,12,m[s[10]],m[s[11]])
        _b2G(v,2,7, 8,13,m[s[12]],m[s[13]]); _b2G(v,3,4,9,14,m[s[14]],m[s[15]])
    for i in range(8): h[i]^=v[i]^v[i+8]

def blake2b_pure(data, digest_size=32, num_rounds=10):
    BLOCK=128; h=list(BLAKE2B_IV)
    h[0]^=(digest_size)|(1<<16)|(1<<24)
    n=len(data)
    if n==0: _b2_compress(h, bytes(BLOCK), 0, True, num_rounds)
    else:
        pos=0
        while pos<n:
            blk=data[pos:pos+BLOCK]; pos+=BLOCK
            blk=blk.ljust(BLOCK,b'\x00')
            _b2_compress(h, blk, min(pos,n), pos>=n, num_rounds)
    return b''.join(h[i].to_bytes(8,'little') for i in range(8))[:digest_size]



# 3 — HELPERS


def to_bits(b):        return ''.join(f'{x:08b}' for x in b)
def byte_entropy(b):
    c=Counter(b); t=len(b)
    return -sum((v/t)*log2(v/t) for v in c.values()) if t>1 else 0.0
def avalanche_pct(h1,h2):
    return round(sum(bin(x^y).count('1') for x,y in zip(h1,h2))/(len(h1)*8)*100,3)

def nist_monobit(bits):
    n=len(bits); s=sum(1 if b=='1' else -1 for b in bits)
    return round(float(math.erfc(abs(s)/math.sqrt(2*n))),6)
def nist_runs(bits):
    n=len(bits); pi=bits.count('1')/n
    if abs(pi-.5)>2/sqrt(n): return 0.0
    runs=1+sum(bits[i]!=bits[i-1] for i in range(1,n))
    exp=2*n*pi*(1-pi)+1; var=2*n*pi*(1-pi)*(2*n*pi*(1-pi)-1)/(n-1)
    return round(float(2*(1-stats.norm.cdf(abs((runs-exp)/sqrt(var))))),6)
def nist_block_freq(bits, block=128):
    n=len(bits); nb=n//block
    if nb==0: return None
    chi=sum(((bits[i*block:(i+1)*block].count('1')-block/2)**2)*4/block for i in range(nb))
    return round(float(1-stats.chi2.cdf(chi,df=nb)),6)
def nist_cumsum(bits):
    x=np.array([1 if b=='1' else -1 for b in bits])
    return round(float(2*(1-stats.norm.cdf(np.max(np.abs(np.cumsum(x)))/sqrt(len(bits))))),6)
def run_nist(fn, n=1000):
    bits=''.join(to_bits(fn(os.urandom(64))) for _ in range(n))
    return {'Monobit':nist_monobit(bits),'Runs':nist_runs(bits),
            'Block Freq':nist_block_freq(bits),'Cumul Sums':nist_cumsum(bits)}
def nist_pass(r): return sum(1 for v in r.values() if v and v>0.01)

def measure_throughput_mem(fn, size, reps=4):
    data=os.urandom(size); times=[]
    for _ in range(reps):
        t0=time.perf_counter(); fn(data); times.append(time.perf_counter()-t0)
    return round((size/1e6)/np.mean(times),4)

def hash_file_chunked(filepath, algo='sha3_256'):
    """Hash a real file in 64KB chunks. Returns (hex_digest, MB/s)."""
    h=hashlib.new(algo); size=os.path.getsize(filepath)
    t0=time.perf_counter()
    with open(filepath,'rb') as f:
        for chunk in iter(lambda: f.read(65536), b''): h.update(chunk)
    elapsed=time.perf_counter()-t0
    return h.hexdigest(), round((size/1e6)/elapsed if elapsed>0 else 0, 3)



# 4 — VERIFICATION


def verify():
    print("="*62)
    print("STEP 0 -- Verifying implementations")
    print("="*62)
    ok=True
    for tv in [b"", b"IIT Jodhpur", os.urandom(300)]:
        if sha3_pure(tv,24,136,32)!=hashlib.sha3_256(tv).digest(): ok=False
    print(f"  SHA3-pure vs hashlib.sha3_256   : {'PASS' if ok else 'FAIL'}")
    tv=b"determinism check"
    det=blake2b_pure(tv,32,10)==blake2b_pure(tv,32,10)
    print(f"  BLAKE2-pure determinism check   : {'PASS' if det else 'FAIL'}")
    if HAS_BLAKE3:
        # Official BLAKE3 known-answer test vector for the empty input.
        b3_ok = b3_digest(b"").hex() == \
            "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262"
        print(f"  BLAKE3 known-answer (empty)     : {'PASS' if b3_ok else 'FAIL'}")
    else:
        print(f"  BLAKE3 known-answer (empty)     : SKIPPED (package missing)")
    print()
    return ok



# Q1 — FILE HASHING (synthetic + real file if uploaded)


def run_q1_file_hashing():
    print("\n"+"="*62)
    print("Q1 -- SHA-3 vs BLAKE2 on files 1KB to 10MB")
    print("="*62)

    # synthetic files
    sizes = {'1KB':1_000,'10KB':10_000,'100KB':100_000,
             '1MB':1_000_000,'10MB':10_000_000}
    rows=[]
    for lbl,sz in sizes.items():
        data=os.urandom(sz)
        t_sha3=[]; t_b2=[]; t_b3=[]
        for _ in range(3):
            t0=time.perf_counter(); hashlib.sha3_256(data).digest(); t_sha3.append(time.perf_counter()-t0)
            t0=time.perf_counter(); hashlib.blake2b(data,digest_size=32).digest(); t_b2.append(time.perf_counter()-t0)
            if HAS_BLAKE3:
                t0=time.perf_counter(); b3_digest(data); t_b3.append(time.perf_counter()-t0)
        sha3_mbs=round((sz/1e6)/np.mean(t_sha3),2)
        b2_mbs  =round((sz/1e6)/np.mean(t_b2),2)
        b3_mbs  =round((sz/1e6)/np.mean(t_b3),2) if HAS_BLAKE3 else 0.0
        # avalanche
        flip=bytearray(data); flip[0]^=0x01; flip=bytes(flip)
        sha3_av=avalanche_pct(hashlib.sha3_256(data).digest(), hashlib.sha3_256(flip).digest())
        b2_av  =avalanche_pct(hashlib.blake2b(data,digest_size=32).digest(),
                              hashlib.blake2b(flip,digest_size=32).digest())
        b3_av  =avalanche_pct(b3_digest(data), b3_digest(flip)) if HAS_BLAKE3 else 0.0
        rows.append({'Size':lbl,'SHA3 MB/s':sha3_mbs,'BLAKE2 MB/s':b2_mbs,'BLAKE3 MB/s':b3_mbs,
                     'BLAKE2/SHA3':round(b2_mbs/sha3_mbs,2),
                     'BLAKE3/SHA3':round(b3_mbs/sha3_mbs,2) if sha3_mbs else 0.0,
                     'SHA3 Aval%':sha3_av,'BLAKE2 Aval%':b2_av,'BLAKE3 Aval%':b3_av})
        print(f"  {lbl:6s}  SHA3:{sha3_mbs:7.1f}  BLAKE2:{b2_mbs:7.1f}  BLAKE3:{b3_mbs:7.1f} MB/s  "
              f"(B2 {round(b2_mbs/sha3_mbs,2)}x, B3 {round(b3_mbs/sha3_mbs,2) if sha3_mbs else 0}x vs SHA3)")

    df = pd.DataFrame(rows)

    # real file upload (Colab)
    print("\n  -- Real file hashing --")
    real_results = {}
    uploaded_files = []
    try:
        import glob
        # check if any user file was uploaded to Colab
        for ext in ['*.pdf','*.png','*.jpg','*.txt','*.csv','*.exe','*.bin','*.zip']:
            uploaded_files.extend(glob.glob(f'/content/{ext}'))
        if uploaded_files:
            for fp in uploaded_files[:3]:   # hash up to 3 uploaded files
                fname = os.path.basename(fp)
                size_mb = round(os.path.getsize(fp)/1e6, 3)
                sha3_hex, sha3_mbs = hash_file_chunked(fp, 'sha3_256')
                b2_hex,   b2_mbs   = hash_file_chunked(fp, 'blake2b')
                print(f"  {fname} ({size_mb} MB)")
                print(f"    SHA3-256 : {sha3_hex[:32]}...  {sha3_mbs} MB/s")
                print(f"    BLAKE2b  : {b2_hex[:32]}...  {b2_mbs} MB/s")
                rec={'size_mb':size_mb,'sha3_mbs':sha3_mbs,'b2_mbs':b2_mbs}
                if HAS_BLAKE3:
                    with open(fp,'rb') as fh: blob=fh.read()
                    t0=time.perf_counter(); b3_hex=b3_digest(blob).hex()
                    b3_mbs=round((size_mb)/(time.perf_counter()-t0),2) if size_mb else 0.0
                    print(f"    BLAKE3   : {b3_hex[:32]}...  {b3_mbs} MB/s")
                    rec['b3_mbs']=b3_mbs
                print(f"    Hashes match (integrity check): {sha3_hex!=b2_hex} (different algos = different digests, both deterministic)")
                real_results[fname] = rec
        else:
            print("  No user files found in /content/. To hash a real file:")
            print("  1. Click the folder icon on the left in Colab")
            print("  2. Upload any file (PDF, image, CSV, etc.)")
            print("  3. Re-run this cell -- it will be detected and hashed automatically.")
    except Exception as e:
        print(f"  File scan skipped: {e}")

    return df, real_results



# Q2 — THROUGHPUT EFFICIENCY (operations per second)


def run_q2_efficiency():
    print("\n"+"="*62)
    print("Q2 -- Which algorithm handles more operations efficiently")
    print("="*62)

    n_ops = 10000
    data_sizes = [64, 256, 1024]   # bytes per operation
    rows=[]
    for sz in data_sizes:
        payloads=[os.urandom(sz) for _ in range(n_ops)]
        t0=time.perf_counter()
        for p in payloads: hashlib.sha3_256(p).digest()
        sha3_t=time.perf_counter()-t0

        t0=time.perf_counter()
        for p in payloads: hashlib.blake2b(p,digest_size=32).digest()
        b2_t=time.perf_counter()-t0

        sha3_ops=round(n_ops/sha3_t)
        b2_ops  =round(n_ops/b2_t)
        row={'Input size':f'{sz}B','SHA3 ops/s':sha3_ops,'BLAKE2 ops/s':b2_ops,
             'BLAKE2 faster':f"{round(b2_ops/sha3_ops,2)}x"}
        if HAS_BLAKE3:
            t0=time.perf_counter()
            for p in payloads: b3_digest(p)
            b3_t=time.perf_counter()-t0
            b3_ops=round(n_ops/b3_t)
            row['BLAKE3 ops/s']=b3_ops
            row['BLAKE3 faster']=f"{round(b3_ops/sha3_ops,2)}x"
        rows.append(row)
        msg=(f"  {sz:5}B per op : SHA3={sha3_ops:,}  BLAKE2={b2_ops:,}"
             f"  ({round(b2_ops/sha3_ops,2)}x)")
        if HAS_BLAKE3: msg+=f"  BLAKE3={b3_ops:,}  ({round(b3_ops/sha3_ops,2)}x)"
        print(msg)

    df=pd.DataFrame(rows)
    print(f"\n  BLAKE2 consistently outperforms SHA-3 on hash throughput at all input sizes.")
    return df



# Q3 — KEYED HASHING: BLAKE2 Native MAC vs HMAC-SHA3


def run_q3_mac():
    print("\n"+"="*62)
    print("Q3 -- BLAKE2 Native MAC vs HMAC-SHA3")
    print("="*62)
    print("  BLAKE2 has a built-in key parameter (native MAC).")
    print("  SHA-3 has no native key -- needs HMAC wrapper from Python hmac module.")

    key     = os.urandom(32)
    n       = 2000
    payloads= [os.urandom(random.choice([64,256,1024])) for _ in range(n)]

    # BLAKE2 native MAC
    t0=time.perf_counter()
    b2_macs=[hashlib.blake2b(p,key=key,digest_size=32).digest() for p in payloads]
    b2_t=time.perf_counter()-t0

    # HMAC-SHA3
    t0=time.perf_counter()
    sha3_macs=[hmac.new(key,p,digestmod=hashlib.sha3_256).digest() for p in payloads]
    sha3_t=time.perf_counter()-t0

    b2_us   = round(b2_t/n*1e6,2)
    sha3_us = round(sha3_t/n*1e6,2)
    speedup = round(sha3_t/b2_t,2)

    # BLAKE3 native keyed MAC (also keyed natively, no HMAC wrapper needed)
    b3_us=None; b3_speedup=None
    if HAS_BLAKE3:
        t0=time.perf_counter()
        b3_macs=[b3_keyed(p,key) for p in payloads]
        b3_t=time.perf_counter()-t0
        b3_us=round(b3_t/n*1e6,2)
        b3_speedup=round(sha3_t/b3_t,2)

    print(f"\n  Speed comparison ({n} operations, mixed 64/256/1024B payloads):")
    print(f"    BLAKE2 native MAC  : {b2_us} microseconds per operation")
    if HAS_BLAKE3:
        print(f"    BLAKE3 native MAC  : {b3_us} microseconds per operation")
    print(f"    HMAC-SHA3 wrapper  : {sha3_us} microseconds per operation")
    print(f"    BLAKE2 speedup     : {speedup}x faster than HMAC-SHA3")
    if HAS_BLAKE3:
        print(f"    BLAKE3 speedup     : {b3_speedup}x faster than HMAC-SHA3")

    # tamper detection test
    tampered=payloads[0][:-1]+bytes([payloads[0][-1]^0xFF])
    b2_detect  = b2_macs[0]   != hashlib.blake2b(tampered,key=key,digest_size=32).digest()
    sha3_detect= sha3_macs[0] != hmac.new(key,tampered,digestmod=hashlib.sha3_256).digest()
    b3_detect  = (b3_macs[0]  != b3_keyed(tampered,key)) if HAS_BLAKE3 else None
    print(f"\n  Tamper detection (1 byte changed in payload):")
    print(f"    BLAKE2 native MAC detects tampering : {b2_detect}")
    if HAS_BLAKE3:
        print(f"    BLAKE3 native MAC detects tampering : {b3_detect}")
    print(f"    HMAC-SHA3 detects tampering         : {sha3_detect}")
    print(f"    All detect equally well (as expected)")

    # security: key confusion test
    wrong_key=os.urandom(32)
    b2_wrong  = hashlib.blake2b(payloads[0],key=wrong_key,digest_size=32).digest()
    sha3_wrong= hmac.new(wrong_key,payloads[0],digestmod=hashlib.sha3_256).digest()
    print(f"\n  Wrong key produces different MAC:")
    print(f"    BLAKE2 native: {b2_macs[0].hex()[:24]}... != {b2_wrong.hex()[:24]}...")
    if HAS_BLAKE3:
        b3_wrong=b3_keyed(payloads[0],wrong_key)
        print(f"    BLAKE3 native: {b3_macs[0].hex()[:24]}... != {b3_wrong.hex()[:24]}...")
    print(f"    HMAC-SHA3    : {sha3_macs[0].hex()[:24]}... != {sha3_wrong.hex()[:24]}...")

    print(f"\n  Summary:")
    print(f"    BLAKE2 native MAC is {speedup}x faster because it has no wrapper overhead.")
    if HAS_BLAKE3:
        print(f"    BLAKE3 native MAC is {b3_speedup}x faster -- also keyed natively (no HMAC).")
    print(f"    HMAC-SHA3 is a two-layer construct: HMAC(SHA3(...)). Adds one hash call overhead.")
    print(f"    Security: all correctly detect tampering and reject wrong keys.")
    print(f"    Recommendation: a native keyed hash (BLAKE2/BLAKE3) for throughput-critical MACs.")

    out={'b2_us':b2_us,'sha3_us':sha3_us,'speedup':speedup,
         'b2_detect':b2_detect,'sha3_detect':sha3_detect}
    if HAS_BLAKE3:
        out.update({'b3_us':b3_us,'b3_speedup':b3_speedup,'b3_detect':b3_detect})
    return out



# Q4 — PARALLEL SPEEDUP


def _sha3_worker(chunk): return [hashlib.sha3_256(d).hexdigest() for d in chunk]
def _b2_worker(chunk):   return [hashlib.blake2b(d,digest_size=32).hexdigest() for d in chunk]

def run_q4_parallel(n=6000):
    print("\n"+"="*62)
    print(f"Q4 -- Parallel Speedup ({n} items, 256B each)")
    print("="*62)
    print("  SHA-3 uses a sequential sponge -- each block depends on the previous.")
    print("  BLAKE2 is embarrassingly parallel -- independent inputs can be split across cores.")
    print("  We test by distributing work across 1, 2, 4 CPU cores.\n")

    data=[os.urandom(256) for _ in range(n)]
    max_cores=min(multiprocessing.cpu_count(),4)
    core_list=[c for c in [1,2,4] if c<=max_cores]
    rows=[]; base_s=base_b=None

    for cores in core_list:
        sz=n//cores
        chunks=[data[i*sz:(i+1)*sz] for i in range(cores)]

        t0=time.perf_counter()
        with multiprocessing.Pool(cores) as pool: pool.map(_sha3_worker,chunks)
        sha3_t=round(time.perf_counter()-t0,4)

        t0=time.perf_counter()
        with multiprocessing.Pool(cores) as pool: pool.map(_b2_worker,chunks)
        b2_t=round(time.perf_counter()-t0,4)

        if cores==1: base_s=sha3_t; base_b=b2_t
        sha3_sp=round(base_s/sha3_t,2); b2_sp=round(base_b/b2_t,2)
        rows.append({'Cores':cores,'SHA3 Time(s)':sha3_t,'BLAKE2 Time(s)':b2_t,
                     'SHA3 Speedup':sha3_sp,'BLAKE2 Speedup':b2_sp})
        print(f"  {cores} core(s) : SHA3={sha3_t:.4f}s (x{sha3_sp})  "
              f"BLAKE2={b2_t:.4f}s (x{b2_sp})")

    df=pd.DataFrame(rows)
    print(f"\n  Note: above, both algorithms parallelize similarly because we distribute")
    print(f"  independent inputs (not splitting a single file) across processes.")

    # --- BLAKE3 single-file internal multithreading -----------------------
    # This is what neither SHA-3 nor plain BLAKE2b can do: BLAKE3's Merkle-tree
    # mode hashes ONE large input across multiple threads internally.
    b3_single={}
    if HAS_BLAKE3:
        print("\n  -- BLAKE3 single-file multithreading (one large buffer) --")
        big=os.urandom(64_000_000)   # 64 MB single input
        def _time_b3(threads,reps=3):
            best=min((_timed(big,threads) for _ in range(reps)))
            return best
        def _timed(buf,threads):
            t0=time.perf_counter(); _blake3(buf,max_threads=threads).digest(); return time.perf_counter()-t0
        t1=_time_b3(1)
        tA=_time_b3(_blake3.AUTO)
        mbps1=round(64/t1,1); mbpsA=round(64/tA,1)
        speedup=round(t1/tA,2) if tA>0 else 1.0
        ncpu=multiprocessing.cpu_count()
        print(f"    64 MB, 1 thread     : {t1*1000:7.1f} ms  ({mbps1} MB/s)")
        print(f"    64 MB, AUTO threads : {tA*1000:7.1f} ms  ({mbpsA} MB/s)")
        print(f"    Single-file speedup : {speedup}x  (machine has {ncpu} core(s))")
        print(f"    SHA-3 / BLAKE2b cannot do this -- a single hash is strictly sequential.")
        b3_single={'mb':64,'t1_ms':round(t1*1000,1),'tA_ms':round(tA*1000,1),
                   'mbps1':mbps1,'mbpsA':mbpsA,'speedup':speedup,'cores':ncpu}
    else:
        print("\n  -- BLAKE3 single-file multithreading skipped (package missing) --")

    print(f"\n  Takeaway: for many independent messages, all three scale across processes.")
    print(f"  For ONE big file, only BLAKE3 parallelizes internally (BLAKE2bp would too).")
    return df, b3_single



# Q5 — MODIFICATIONS (security-performance tradeoff)


VARIANTS = {
    'SHA3-256 (Original)':  {'fn':lambda d:hashlib.sha3_256(d).digest(),       'family':'SHA3', 'type':'original',    'digest':32,'cap_bits':512,  'desc':'24 rounds | rate=136B | capacity=512b'},
    'SHA3-ReducedRounds':   {'fn':lambda d:sha3_pure(d,16,136,32),             'family':'SHA3', 'type':'performance', 'digest':32,'cap_bits':512,  'desc':'16 rounds | rate=136B | capacity=512b'},
    'SHA3-HighCapacity':    {'fn':lambda d:sha3_pure(d,24,104,32),             'family':'SHA3', 'type':'security',    'digest':32,'cap_bits':768,  'desc':'24 rounds | rate=104B | capacity=768b'},
    'BLAKE2b (Original)':   {'fn':lambda d:hashlib.blake2b(d,digest_size=32).digest(),'family':'BLAKE2','type':'original',  'digest':32,'cap_bits':256,  'desc':'10 rounds | digest=32B'},
    'BLAKE2-FastRounds':    {'fn':lambda d:blake2b_pure(d,32,8),               'family':'BLAKE2','type':'performance','digest':32,'cap_bits':256,  'desc':'8 rounds  | digest=32B'},
    'BLAKE2-LongerDigest':  {'fn':lambda d:hashlib.blake2b(d,digest_size=48).digest(),'family':'BLAKE2','type':'security',  'digest':48,'cap_bits':384,  'desc':'10 rounds | digest=48B'},
}
# BLAKE3 variants (added in extension work). BLAKE3's digest is an XOF, so the
# "longer digest" security variant is just a longer squeeze -- no reimplementation.
if HAS_BLAKE3:
    VARIANTS['BLAKE3 (Original)']    = {'fn':lambda d:b3_digest(d,32), 'family':'BLAKE3','type':'original','digest':32,'cap_bits':256,'desc':'tree mode | digest=32B'}
    VARIANTS['BLAKE3-LongerDigest']  = {'fn':lambda d:b3_digest(d,48), 'family':'BLAKE3','type':'security','digest':48,'cap_bits':384,'desc':'tree mode | digest=48B (XOF)'}

COLORS={'SHA3-256 (Original)':'#A855F7','SHA3-ReducedRounds':'#F97316',
        'SHA3-HighCapacity':'#06B6D4','BLAKE2b (Original)':'#22C55E',
        'BLAKE2-FastRounds':'#EAB308','BLAKE2-LongerDigest':'#EC4899',
        'BLAKE3 (Original)':'#3B82F6','BLAKE3-LongerDigest':'#F43F5E'}

def security_label(cfg): return f"2^{cfg['cap_bits']//2}"

def run_q5_modifications():
    print("\n"+"="*62)
    print("Q5 -- Modifications: Security-Performance Tradeoff")
    print("="*62)

    sha3_base=lambda d: sha3_pure(d,24,136,32)
    b2_base  =lambda d: blake2b_pure(d,32,10)
    FILE_SIZES=[1_000,10_000,100_000,1_000_000]

    results={}
    for name,cfg in VARIANTS.items():
        fn=cfg['fn']
        print(f"\n  {name}  [{cfg['desc']}]")
        tp={sz:measure_throughput_mem(fn,sz) for sz in FILE_SIZES}
        for sz in FILE_SIZES:
            print(f"    {sz//1000:>6}KB  {tp[sz]:>10.4f} MB/s")
        # avalanche
        avs=[];
        for _ in range(300):
            d=os.urandom(random.choice([32,64,128,256]))
            ba=bytearray(d); ba[random.randint(0,len(ba)-1)]^=(1<<random.randint(0,7))
            avs.append(avalanche_pct(fn(d),fn(bytes(ba))))
        av_mean,av_std=round(np.mean(avs),3),round(np.std(avs),3)
        # entropy
        ent=round(np.mean([byte_entropy(fn(os.urandom(64))) for _ in range(100)]),5)
        # nist
        nist=run_nist(fn,n=800); passed=nist_pass(nist)
        sec=security_label(cfg)
        print(f"    Avalanche : {av_mean:.3f}%  Entropy : {ent:.5f}  NIST : {passed}/4  Security : {sec}")

        results[name]={'throughput':tp,'avalanche_mean':av_mean,'avalanche_std':av_std,
                       'avalanche_vals':avs,'entropy':ent,'nist':nist,'nist_passed':passed,
                       'digest':cfg['digest'],'security':sec,'family':cfg['family'],
                       'type':cfg['type'],'desc':cfg['desc'],'cap_bits':cfg['cap_bits']}

    # speedup ratios
    sha3_base_tp={sz:measure_throughput_mem(sha3_base,sz) for sz in FILE_SIZES}
    b2_base_tp  ={sz:measure_throughput_mem(b2_base,sz)   for sz in FILE_SIZES}
    for name in results:
        typ=results[name]['type']; fam=results[name]['family']
        if typ=='original':         results[name]['speedup']='baseline'
        elif fam=='SHA3':
            b=sha3_base_tp[1_000_000]; m=results[name]['throughput'][1_000_000]
            results[name]['speedup']=f"{round(m/b,2)}x" if b>0 else 'N/A'
        elif name=='BLAKE2-FastRounds':
            b=b2_base_tp[1_000_000]; m=results[name]['throughput'][1_000_000]
            results[name]['speedup']=f"{round(m/b,2)}x" if b>0 else 'N/A'
        else: results[name]['speedup']='N/A (hashlib)'
    return results



# 5 — PRINT COMBINED REPORT


def print_full_report(df_q1, real_files, df_q2, q3, df_q4, q5_results, q4_b3=None):
    print("\n\n"+"="*62)
    print("FULL REPORT -- ALL 5 PROBLEM STATEMENT QUESTIONS")
    print("="*62)

    print("\nQ1 -- File Hashing Performance (SHA-3 vs BLAKE2 vs BLAKE3)")
    print(df_q1.to_string(index=False))
    if real_files:
        print("\n  Real file results:")
        for fname, r in real_files.items():
            extra=f"  BLAKE3={r['b3_mbs']} MB/s" if 'b3_mbs' in r else ""
            print(f"    {fname}: {r['size_mb']}MB  SHA3={r['sha3_mbs']} MB/s  BLAKE2={r['b2_mbs']} MB/s{extra}")

    print("\nQ2 -- Operations Per Second")
    print(df_q2.to_string(index=False))

    print("\nQ3 -- Keyed Hashing (MAC)")
    print(f"  BLAKE2 native MAC  : {q3['b2_us']} us/op")
    if 'b3_us' in q3:
        print(f"  BLAKE3 native MAC  : {q3['b3_us']} us/op")
    print(f"  HMAC-SHA3 wrapper  : {q3['sha3_us']} us/op")
    print(f"  BLAKE2 speedup     : {q3['speedup']}x vs HMAC-SHA3")
    if 'b3_speedup' in q3:
        print(f"  BLAKE3 speedup     : {q3['b3_speedup']}x vs HMAC-SHA3")
    print(f"  Tamper detection   : BLAKE2={q3['b2_detect']}  SHA3={q3['sha3_detect']}"
          + (f"  BLAKE3={q3['b3_detect']}" if 'b3_detect' in q3 else ""))

    print("\nQ4 -- Parallel Benchmark (independent inputs across processes)")
    print(df_q4.to_string(index=False))
    if q4_b3:
        print(f"\n  Q4b -- BLAKE3 single-file multithreading ({q4_b3['mb']} MB, {q4_b3['cores']} core(s)):")
        print(f"    1 thread: {q4_b3['mbps1']} MB/s   AUTO threads: {q4_b3['mbpsA']} MB/s"
              f"   -> {q4_b3['speedup']}x on one file")

    print("\nQ5 -- Modifications Summary")
    rows=[]
    for n,r in q5_results.items():
        tp=r['throughput'].get(1_000_000,0)
        rows.append({'Variant':n,'Goal':r['type'].upper(),'1MB MB/s':round(tp,4),
                     'Avalanche%':r['avalanche_mean'],'Entropy':r['entropy'],
                     'NIST':f"{r['nist_passed']}/4",'Security':r['security'],
                     'Speedup':r['speedup']})
    print(pd.DataFrame(rows).to_string(index=False))



# 6 — COMBINED PLOT


def plot_all(df_q1, df_q2, q3, df_q4, q5_results, q4_b3=None):
    fig=plt.figure(figsize=(20,14),constrained_layout=True)
    fig.patch.set_facecolor('#0D0D2B')
    gs=gridspec.GridSpec(3,3,figure=fig)

    def ax_setup(ax,title):
        ax.set_facecolor('#14082E')
        ax.set_title(title,color='white',fontsize=9,fontweight='bold',pad=5)
        ax.tick_params(colors='#CCCCCC',labelsize=7)
        for sp in ax.spines.values(): sp.set_edgecolor('#374151')

    # (0,0) Q1 throughput
    ax=fig.add_subplot(gs[0,0]); ax_setup(ax,'Q1 -- File Throughput SHA3 vs BLAKE2 vs BLAKE3')
    x=range(len(df_q1))
    ax.plot(list(x),df_q1['SHA3 MB/s'].tolist(),'o-',color='#A855F7',lw=2,ms=5,label='SHA3-256')
    ax.plot(list(x),df_q1['BLAKE2 MB/s'].tolist(),'s-',color='#22C55E',lw=2,ms=5,label='BLAKE2b')
    if 'BLAKE3 MB/s' in df_q1.columns and df_q1['BLAKE3 MB/s'].sum()>0:
        ax.plot(list(x),df_q1['BLAKE3 MB/s'].tolist(),'^-',color='#3B82F6',lw=2,ms=5,label='BLAKE3')
    ax.set_xticks(list(x)); ax.set_xticklabels(df_q1['Size'].tolist(),color='#CCCCCC',fontsize=7)
    ax.set_ylabel('MB/s',color='#CCCCCC',fontsize=8)
    ax.legend(facecolor='#1E0A3C',labelcolor='white',fontsize=7)
    ax.grid(True,color='#374151',alpha=0.4)

    # (0,1) Q2 ops/s
    ax=fig.add_subplot(gs[0,1]); ax_setup(ax,'Q2 -- Operations per Second')
    x2=np.arange(len(df_q2))
    has_b3_q2='BLAKE3 ops/s' in df_q2.columns
    w=0.26 if has_b3_q2 else 0.35
    if has_b3_q2:
        ax.bar(x2-w,df_q2['SHA3 ops/s'].tolist(),w,color='#A855F7',label='SHA3-256')
        ax.bar(x2,  df_q2['BLAKE2 ops/s'].tolist(),w,color='#22C55E',label='BLAKE2b')
        ax.bar(x2+w,df_q2['BLAKE3 ops/s'].tolist(),w,color='#3B82F6',label='BLAKE3')
    else:
        ax.bar(x2-w/2,df_q2['SHA3 ops/s'].tolist(),w,color='#A855F7',label='SHA3-256')
        ax.bar(x2+w/2,df_q2['BLAKE2 ops/s'].tolist(),w,color='#22C55E',label='BLAKE2b')
    ax.set_xticks(list(x2)); ax.set_xticklabels(df_q2['Input size'].tolist(),color='#CCCCCC',fontsize=8)
    ax.set_ylabel('ops/s',color='#CCCCCC',fontsize=8)
    ax.legend(facecolor='#1E0A3C',labelcolor='white',fontsize=7)
    ax.grid(True,color='#374151',alpha=0.4)

    # (0,2) Q3 MAC speed
    ax=fig.add_subplot(gs[0,2]); ax_setup(ax,'Q3 -- MAC Speed: Native vs HMAC-SHA3')
    if 'b3_us' in q3:
        labels=['BLAKE2\nNative','BLAKE3\nNative','HMAC-SHA3\nWrapper']
        vals=[q3['b2_us'],q3['b3_us'],q3['sha3_us']]
        cols=['#22C55E','#3B82F6','#A855F7']
    else:
        labels=['BLAKE2\nNative MAC','HMAC-SHA3\nWrapper']
        vals=[q3['b2_us'],q3['sha3_us']]; cols=['#22C55E','#A855F7']
    bars=ax.bar(labels,vals,color=cols,width=0.5)
    for bar,v in zip(bars,vals):
        ax.text(bar.get_x()+bar.get_width()/2,bar.get_height()+0.05,
                f'{v} us',ha='center',va='bottom',color='white',fontsize=8,fontweight='bold')
    ax.set_ylabel('Microseconds per op',color='#CCCCCC',fontsize=8)
    ax.tick_params(colors='#CCCCCC')
    ax.grid(True,color='#374151',alpha=0.4)

    # (1,0) Q4 parallel speedup
    ax=fig.add_subplot(gs[1,0]); ax_setup(ax,'Q4 -- Parallel Speedup vs 1 Core')
    if not df_q4.empty:
        ax.plot(df_q4['Cores'].tolist(),df_q4['SHA3 Speedup'].tolist(),'o-',color='#A855F7',lw=2,ms=6,label='SHA3 (multi-input)')
        ax.plot(df_q4['Cores'].tolist(),df_q4['BLAKE2 Speedup'].tolist(),'s-',color='#22C55E',lw=2,ms=6,label='BLAKE2 (multi-input)')
        ax.plot(df_q4['Cores'].tolist(),df_q4['Cores'].tolist(),'--',color='#6B7280',lw=1,label='Ideal')
        ax.set_xticks(df_q4['Cores'].tolist())
    if q4_b3:
        ax.text(0.5,0.97,
                f"BLAKE3 single-file (1 hash):\n{q4_b3['speedup']}x at AUTO threads\n"
                f"({q4_b3['mbps1']}->{q4_b3['mbpsA']} MB/s, {q4_b3['cores']} core)",
                transform=ax.transAxes,ha='center',va='top',color='#3B82F6',fontsize=6.5,
                fontweight='bold',bbox=dict(boxstyle='round',fc='#0D1B3C',ec='#3B82F6',lw=1))
    ax.set_xlabel('CPU Cores',color='#CCCCCC',fontsize=8)
    ax.set_ylabel('Speedup vs 1 Core',color='#CCCCCC',fontsize=8)
    ax.legend(facecolor='#1E0A3C',labelcolor='white',fontsize=6,loc='lower right')
    ax.grid(True,color='#374151',alpha=0.4)

    # (1,1) Q5 SHA3 NIST
    ax=fig.add_subplot(gs[1,1]); ax_setup(ax,'Q5 -- NIST p-values SHA-3 Variants')
    sha3_names=[n for n in q5_results if q5_results[n]['family']=='SHA3']
    tests=list(q5_results[sha3_names[0]]['nist'].keys())
    xs=np.arange(len(tests)); w2=0.28
    for idx,n in enumerate(sha3_names):
        pvs=[q5_results[n]['nist'].get(t,0) or 0 for t in tests]
        ax.bar(xs+w2*(idx-1),pvs,w2,color=COLORS[n],
               label=n.replace(' (Original)',' orig').replace('SHA3-',''))
    ax.axhline(0.01,color='#F87171',ls='--',lw=1.5,label='a=0.01')
    ax.set_xticks(xs); ax.set_xticklabels(tests,color='#CCCCCC',fontsize=7)
    ax.set_ylabel('p-value',color='#CCCCCC',fontsize=8)
    ax.legend(facecolor='#1E0A3C',labelcolor='white',fontsize=6)
    ax.grid(True,color='#374151',alpha=0.4)

    # (1,2) Q5 BLAKE2 + BLAKE3 NIST
    ax=fig.add_subplot(gs[1,2]); ax_setup(ax,'Q5 -- NIST p-values BLAKE2 & BLAKE3 Variants')
    b2_names=[n for n in q5_results if q5_results[n]['family'] in ('BLAKE2','BLAKE3')]
    m=len(b2_names); gw=0.8; bw=gw/max(m,1)
    for idx,n in enumerate(b2_names):
        pvs=[q5_results[n]['nist'].get(t,0) or 0 for t in tests]
        off=(idx-(m-1)/2)*bw
        ax.bar(xs+off,pvs,bw,color=COLORS[n],
               label=n.replace(' (Original)',' orig').replace('BLAKE2','B2').replace('BLAKE3','B3'))
    ax.axhline(0.01,color='#F87171',ls='--',lw=1.5,label='a=0.01')
    ax.set_xticks(xs); ax.set_xticklabels(tests,color='#CCCCCC',fontsize=7)
    ax.set_ylabel('p-value',color='#CCCCCC',fontsize=8)
    ax.legend(facecolor='#1E0A3C',labelcolor='white',fontsize=5)
    ax.grid(True,color='#374151',alpha=0.4)

    # (2,0) Q5 avalanche
    ax=fig.add_subplot(gs[2,0]); ax_setup(ax,'Q5 -- Avalanche: All Variants')
    names=list(q5_results.keys())
    _shortmap={'SHA3-256 (Original)':'SHA3-orig','SHA3-ReducedRounds':'SHA3-R16',
               'SHA3-HighCapacity':'SHA3-HiCap','BLAKE2b (Original)':'B2-orig',
               'BLAKE2-FastRounds':'B2-Fast8','BLAKE2-LongerDigest':'B2-Long48',
               'BLAKE3 (Original)':'B3-orig','BLAKE3-LongerDigest':'B3-Long48'}
    short=[_shortmap.get(n,n) for n in names]
    means=[q5_results[n]['avalanche_mean'] for n in names]
    stds =[q5_results[n]['avalanche_std']  for n in names]
    cols =[COLORS[n] for n in names]
    ax.bar(range(len(names)),means,color=cols,yerr=stds,capsize=3,width=0.6,
           error_kw={'ecolor':'#CCCCCC','lw':1})
    ax.axhline(50,color='#F87171',ls='--',lw=1.5,label='Ideal 50%')
    ax.set_xticks(range(len(names))); ax.set_xticklabels(short,color='#CCCCCC',fontsize=6,rotation=20,ha='right')
    ax.set_ylim(40,60); ax.set_ylabel('Avalanche %',color='#CCCCCC',fontsize=8)
    ax.legend(facecolor='#1E0A3C',labelcolor='white',fontsize=7)
    ax.grid(True,color='#374151',alpha=0.4)

    # (2,1) Q5 entropy
    ax=fig.add_subplot(gs[2,1]); ax_setup(ax,'Q5 -- Byte Entropy: All Variants')
    ents=[q5_results[n]['entropy'] for n in names]
    bars2=ax.bar(range(len(names)),ents,color=cols,width=0.6)
    ax.axhline(8.0,color='#FBBF24',ls='--',lw=1.5,label='Max=8.0')
    for bar,v in zip(bars2,ents):
        ax.text(bar.get_x()+bar.get_width()/2,bar.get_height()+0.002,f'{v:.3f}',
                ha='center',va='bottom',color='white',fontsize=6)
    ax.set_xticks(range(len(names))); ax.set_xticklabels(short,color='#CCCCCC',fontsize=6,rotation=20,ha='right')
    ax.set_ylim(4.7,8.1); ax.set_ylabel('bits/byte',color='#CCCCCC',fontsize=8)
    ax.legend(facecolor='#1E0A3C',labelcolor='white',fontsize=7)
    ax.grid(True,color='#374151',alpha=0.4)

    # (2,2) Q5 security vs throughput scatter
    ax=fig.add_subplot(gs[2,2]); ax_setup(ax,'Q5 -- Security vs Throughput Tradeoff')
    for n in names:
        r=q5_results[n]; tp=r['throughput'].get(1_000_000,0); sec=r['cap_bits']//2
        ax.scatter(tp,sec,color=COLORS[n],s=90,zorder=5,
                   marker='o' if r['family']=='SHA3' else 's')
        ax.annotate(n.replace(' (Original)',''),
                    (tp,sec),textcoords='offset points',xytext=(5,3),
                    fontsize=6.5,color=COLORS[n])
    ax.set_xlabel('Throughput at 1MB (MB/s)',color='#CCCCCC',fontsize=8)
    ax.set_ylabel('Collision resistance (bits)',color='#CCCCCC',fontsize=8)
    ax.grid(True,color='#374151',alpha=0.4)

    fig.suptitle(
        'SHA-3 vs BLAKE2 -- Complete Semester 2 Analysis | '
        'B. Jyothirmayi | M24AID016 | IIT Jodhpur',
        color='white',fontsize=11,fontweight='bold')

    out='sem2_output/sem2_complete_results.png'
    plt.savefig(out,dpi=150,bbox_inches='tight',facecolor='#0D0D2B')
    plt.show()
    print(f"\n  Chart saved -> {out}")



# 7 — SIMPLE UI (Gradio)   [added in extension work]

# Install once:  !pip install gradio -q
# Then run in a separate cell:  launch_ui()
# Lets you type text (or upload a file) and hash it through SHA-3, BLAKE2b
# and BLAKE3 side by side, and demonstrates BLAKE3 single-file parallelism.

try:
    import gradio as gr
    HAS_GRADIO = True
except ImportError:
    HAS_GRADIO = False


def _one_bit_flip(data: bytes) -> bytes:
    if not data:
        return b"\x01"
    ba = bytearray(data); ba[0] ^= 0x01
    return bytes(ba)


def _analyze_variant(fn, sample, n_nist=400):
    """Full analysis of one variant on the given input sample.
    NIST bits are generated the same way as the code output: by hashing
    (input + counter) repeatedly, matching the user-input testing methodology."""
    digests = [fn(sample + i.to_bytes(4, 'little')) for i in range(n_nist)]
    bits = ''.join(to_bits(d) for d in digests)
    nist = {'Monobit': nist_monobit(bits), 'Runs': nist_runs(bits),
            'Block Freq': nist_block_freq(bits), 'Cumul Sums': nist_cumsum(bits)}
    passed = nist_pass(nist)
    entropy = round(float(np.mean([byte_entropy(d) for d in digests[:100]])), 3)
    bit_bal = round(bits.count('1') / len(bits) * 100, 2)
    main = fn(sample)
    # average avalanche over several single-bit flips for a stabler estimate
    avs = []
    for pos in range(min(16, len(sample) * 8)):
        ba = bytearray(sample) if sample else bytearray(b"\x00")
        ba[pos // 8] ^= (1 << (pos % 8))
        avs.append(avalanche_pct(main, fn(bytes(ba))))
    aval = round(float(np.mean(avs)), 3)
    return main, aval, entropy, bit_bal, nist, passed


def _time_hash(fn, size=20_000, reps=5):
    """Return (time_ms, MB/s) for hashing a fixed buffer. Best-of-reps for a
    stable, low-noise number so 'which is faster' is unambiguous."""
    data = os.urandom(size)
    times = []
    for _ in range(reps):
        t0 = time.perf_counter(); fn(data); times.append(time.perf_counter() - t0)
    best = min(times)
    ms = round(best * 1000, 3)
    mbs = round((size / 1e6) / best, 2) if best > 0 else 0.0
    return ms, mbs


def ui_hash(text, file_path):
    """Run the input through ALL variants (baseline + modified, incl. BLAKE3)
    and return a full metrics table: digest, throughput, avalanche, entropy,
    bit-balance, every NIST p-value, NIST pass count, and security level."""
    if file_path:
        with open(file_path, "rb") as f:
            data = f.read()
        src = f"file ({len(data):,} bytes)"
    else:
        data = (text or "IIT Jodhpur M.Tech AI - SHA3 vs BLAKE2 vs BLAKE3").encode()
        src = f"text ({len(data):,} bytes)"

    # Cap the sample so the pure-Python modified variants stay fast and digests
    # are directly comparable across variants.
    SAMPLE = data[:512]

    rows = []
    for name, cfg in VARIANTS.items():
        fn = cfg['fn']
        digest, aval, entropy, bit_bal, nist, passed = _analyze_variant(fn, SAMPLE)
        ms, mbs = _time_hash(fn, 20_000)   # explicit time + throughput, fixed buffer
        rows.append({
            'Variant': name,
            'Family': cfg['family'],
            'Goal': cfg['type'],
            'Digest (hex)': digest.hex()[:24] + '...',
            'Bytes': cfg['digest'],
            'Time (ms/20KB)': ms,
            'MB/s': mbs,
            'Avalanche %': aval,
            'Entropy': entropy,
            'Bit-bal %': bit_bal,
            'Monobit': nist['Monobit'],
            'Runs': nist['Runs'],
            'BlockFreq': nist['Block Freq'],
            'CumSum': nist['Cumul Sums'],
            'NIST': f"{passed}/4",
            'Security': security_label(cfg),
        })
    df = pd.DataFrame(rows)

    summary = (f"**Input:** {src}  \n"
               f"_Digest, avalanche, entropy, bit-balance and NIST p-values are computed on the "
               f"first {len(SAMPLE)} bytes of the input (kept small so the pure-Python modified "
               f"variants stay fast). NIST bits are generated by hashing input+counter, 400 times. "
               f"Throughput (MB/s) and Time (ms to hash a fixed 20 KB buffer, best of 5) are measured "
               f"for a fair speed comparison - lower Time / higher MB/s is faster. "
               f"A NIST p-value above 0.01 passes; ideal avalanche is ~50%, ideal bit-balance ~50%._")
    return summary, df


def ui_single_file_parallel(size_mb):
    """Demonstrate BLAKE3 single-file internal multithreading."""
    if not HAS_BLAKE3:
        return "BLAKE3 not installed. Run:  !pip install blake3 -q"
    size_mb = int(size_mb)
    big = os.urandom(size_mb * 1_000_000)

    def timed(threads):
        return min((lambda: (lambda s: (_blake3(big, max_threads=threads).digest(),
                                        time.perf_counter() - s)[1])(time.perf_counter()))()
                   for _ in range(3))
    t1 = timed(1); tA = timed(_blake3.AUTO)
    mbps1 = round(size_mb / t1, 1); mbpsA = round(size_mb / tA, 1)
    speedup = round(t1 / tA, 2) if tA > 0 else 1.0
    cores = multiprocessing.cpu_count()
    return (f"**BLAKE3 single-file multithreading ({size_mb} MB, {cores} core(s))**\n\n"
            f"| Mode | Time | Throughput |\n|---|---|---|\n"
            f"| 1 thread | {t1*1000:.1f} ms | {mbps1} MB/s |\n"
            f"| AUTO threads | {tA*1000:.1f} ms | {mbpsA} MB/s |\n\n"
            f"**Single-file speedup: {speedup}x**  \n"
            f"_SHA-3 and plain BLAKE2b cannot do this - a single hash is strictly sequential. "
            f"Speedup grows with the number of CPU cores (e.g. ~1.5-1.9x on a 2-core Colab runtime)._")


def build_ui():
    """Build (but do not launch) the Gradio interface."""
    with gr.Blocks(title="SHA-3 vs BLAKE2 vs BLAKE3") as demo:
        gr.Markdown("# SHA-3 vs BLAKE2 vs BLAKE3\nHash any text or file and compare the three algorithms.")
        with gr.Tab("Hash & Compare"):
            gr.Markdown("Runs your input through all 8 variants - SHA-3, BLAKE2 and BLAKE3, "
                        "each as baseline + modified - and shows the full metrics including every NIST p-value.")
            txt = gr.Textbox(label="Text to hash", placeholder="Type anything...", lines=2)
            up = gr.File(label="...or upload a file", type="filepath")
            btn = gr.Button("Analyze", variant="primary")
            note = gr.Markdown()
            table = gr.Dataframe(label="Per-variant metrics", wrap=True)
            btn.click(ui_hash, inputs=[txt, up], outputs=[note, table])
        with gr.Tab("BLAKE3 Single-File Parallelism"):
            gr.Markdown("Hash one large buffer with 1 thread vs all available threads.")
            sz = gr.Slider(8, 128, value=32, step=8, label="Buffer size (MB)")
            pbtn = gr.Button("Run parallelism demo", variant="primary")
            pout = gr.Markdown()
            pbtn.click(ui_single_file_parallel, inputs=[sz], outputs=pout)
    return demo


def launch_ui(share=True):
    """Launch the UI (call this in its own Colab cell)."""
    if not HAS_GRADIO:
        print("Gradio not installed. Run:  !pip install gradio -q")
        return
    build_ui().launch(share=share)



# MAIN


if __name__=='__main__':

    print("="*62)

    if not verify():
        raise SystemExit("Verification failed.")

    print("\n[1/5] Q1 -- File hashing (synthetic + real file if uploaded)...")
    df_q1, real_files = run_q1_file_hashing()

    print("\n[2/5] Q2 -- Operations per second efficiency...")
    df_q2 = run_q2_efficiency()

    print("\n[3/5] Q3 -- BLAKE2 native MAC vs HMAC-SHA3...")
    q3 = run_q3_mac()

    print("\n[4/5] Q4 -- Parallel benchmark + BLAKE3 single-file multithreading...")
    df_q4, q4_b3 = run_q4_parallel(n=6000)

    print("\n[5/5] Q5 -- Modifications tradeoff analysis...")
    q5 = run_q5_modifications()

    print_full_report(df_q1, real_files, df_q2, q3, df_q4, q5, q4_b3)

    print("\n[Plotting]...")
    plot_all(df_q1, df_q2, q3, df_q4, q5, q4_b3)

    import json
    report = {
        'Q1_file_hashing': df_q1.to_dict(orient='records'),
        'Q1_real_files': real_files,
        'Q2_efficiency': df_q2.to_dict(orient='records'),
        'Q3_mac': q3,
        'Q4_parallel': df_q4.to_dict(orient='records'),
        'Q4_blake3_single_file': q4_b3,
        'Q5_modifications': {
            n: {'config':r['desc'],'throughput':{f"{k//1000}KB":v for k,v in r['throughput'].items()},
                'speedup':r['speedup'],'avalanche':r['avalanche_mean'],'entropy':r['entropy'],
                'nist':r['nist'],'nist_passed':r['nist_passed'],'security':r['security']}
            for n,r in q5.items()
        },
    }
    with open('sem2_output/sem2_complete_report.json','w') as f:
        json.dump(report,f,indent=2)

    print("\n  JSON -> sem2_output/sem2_complete_report.json")
    print("  PNG  -> sem2_output/sem2_complete_results.png")

    try:
        from google.colab import files
        files.download('sem2_output/sem2_complete_results.png')
        files.download('sem2_output/sem2_complete_report.json')
    except ImportError:
        pass

    print("\n"+"="*62+"  DONE.  "+"="*62)

launch_ui()